tasks:
  - init: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip wheel setuptools
      pip install Django
      pip install dj_database_url psycopg2 django-compressor whitenoise gunicorn
      npm install
      python manage.py migrate
  - command: |
      source venv/bin/activate
      python manage.py runserver
      npm run dev
  
ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
