# Generated by Django 4.2 on 2023-05-13 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holidays', '0002_timeoff_reason_text_timeoff_status_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name_text',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='timeoff',
            name='employee',
        ),
        migrations.AddField(
            model_name='timeoff',
            name='department',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='holidays.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeoff',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
