# Generated by Django 4.2 on 2023-05-13 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0003_rename_name_text_department_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeoff',
            old_name='reason_text',
            new_name='reason',
        ),
        migrations.RenameField(
            model_name='timeoff',
            old_name='status_text',
            new_name='status',
        ),
    ]
